 jobs:
  include:
    - stage: test
      name: "Unit tests"
      language: node_js
      node_js:
        - 12
      install:
        - npm ci
      script:
        - npm test
    - stage: release
      name: "Create release notes with semantic-release"
      language: node_js
      node_js:
        - 12
      script:
        - npx semantic-release
    - stage: deploy
      name: "Deploy to Wejay"
      language: node_js
      node_js:
        - 10
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - export REPO=iteam1337/sonos-wejay
        - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
          ; fi`
        - docker build -f Dockerfile -t $REPO:$TAG .
        - docker push $REPO
stages:
  - test
  - release
    if: branch = master AND type != pull_request
  - deploy
    if: branch = master AND type != pull_request
