language: node_js
cache:
  directories:
    - '~/.npm'
node_js:
  - '10'
install:
  - npm install --silent
script:
  - npm run test:ci
branches:
  only:
    - master
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - secure: r6ytr9nmp8hawwQF5zQ6rnJyDLllWPjNvAqkvSAROA2bWbCCeVDtvp7HJyEGX0dL3HFHD2GUcQRlwIiKywtwSOL6Z9ZhOGPOANNSbuC5ByOA3cXVD5EKF7+VTxYxu8VDrhAXK28hYXt/LIf2Ji3RM8EjWcoC+3EHxcm/r2lWiu8qMURUgdyV2WcmbgPUF9orhMU9cMReQlYsbgaSw++hYLoORmcc35DTGjo3JdU4DRjw+CZeX6JZelmNYcJuSYldvIY0D/P1UDe1MwtYwswWXhwa8YmeAM6DjxucbWdLKOGXSJzmXMJqu89iE6MntpboVwHqa1CHpVBeirlw4jc02dsn8QNABVj7C5GXYKoJ3IbBEw10oqJOy282nWDtTWtog1ZjSK+gupBqbG86v7AyuLJBrlxaOobmp8nRCtUGrV9Wb28OqIlKbPOtYzUSAbu94Gv7UhffGfEwA5qTgQmfUj5BCvYu3m4/N2G5i6y0JzY2wQg2p8HEWDL8rewxNeK0lKMtlBZnzGlsgvHuIKM0SDLoV3173mgg7EuHHwnVv0OoJeU3Zwd5/QH6PoCgGG1rfmpjB8NxCfCc+oXyIlHHmPywMIt6cZYpMkiXj7AsZotesxKXcx1dS/2svm2HKV0iBzO+/YYbeuxZr23WHGOr6D/ZnGShSCN3Pp6AUKGLSjs=
    - secure: ViLpMlQuDxLqbRLNL63WgJ8KT4jmSeM+1ly81u9CVSrsnguWXdNfQFhq2gq6wh6g3qpcz9gY+ta/UlLahmF4AkF0KGnKe0k3H+LApnZ9Ol7mj6KP5bxyUwYeoy1JekKnnEYjxheUPX5eW8kfdOMiwmCxNCr+dGCXYABjQyyYRu2slIEUzAJKLW8eXfgOD8+lUvAxMzEvFJ9LyEWN3p/eik95LJn2UlELYZtTPBReVJEt6qXtxZFGm3nvg3so6esvYTlNHx2dtBP+hkKUqqqCwtCHmKq1xhYZBs6uyPIErGVEEXrpmSa/Tc3bwighJKDt1qT12BM4nE7JEyie6M6QCEKBgeXuQVEYTCputPR+le30jAwO4ajEkbFRvBheBwLZX1DU3lXeSXl0bX2lgk6vh51UQ6+HtwPnH8ZPd/qS3rHvi3Ky94mTZi60URyP6stRoVrFiZERbYZ74a+jGBOgcOWT87f0ACoIQlmnLf10JEw6LXS+SBp2JaWrKfCZEXgVHJutgY/YILGhrB+HGxHi/uBeW2uT7UCVEhWGY3epXHkV4MRK0nLbu4tKxaY+wIlcpbcGF6sAjjCFHTuByasJHjyiLDwcLHC8xi/nmsyPRIkKWUrZ9pqApK+i2F/+ipGmkO/BuYShJBMQr1jGF/CwEKG4RkDn3W7cfoOT1co+xpI=
    - secure: jz4X8rBKed+bmI2J/njmJHQrynQu31F2tpTGfQSaswNyA/mQIJFMnVitp3VqfXFITIL4mQuLJzveXJAfEcVa2eEaZpAjk0Kx0ORfe4xc61AjvUTReldj4b4xqb+6WaIhWDRHzp+QIwVJms2D7Wr2xWiVUTEqTIjWxNL4k/LPyahY/XpBOa9rdPHlXuJvxrceWpdQOgltRvYmbZbQnx7XK5mqM8BIBUDsbGMFFYtOcIOhajp9napzp2T08A+VQV6PWT6rRpP9RslM9EhNgyuHrCbeJFJlxUe1VsUu4cqIHnNtwp7wA1YOUOdi7x/s9dACosudBRXrpQlGgAfC7F27fI4t/kuSrELWfoyQPZ/1D3zWSOXfMoqgmW83IN0olc5fCerpDJWsQK2UA/cmCmjeQMj4TMFeLxJi7F2ye2iJG6GLbLX//3/ZBLHHfIX65h26JHfXrpODhPTWWGKDr/PyyWyfy4Z3z0pv1OIMCJHdiYV7nHxNFYsw2K9VJ+u8Cxb+4gjOrreUuUrX8bYodkrSwPxNSSVWSGMs2ooc0ha86liOyBcnupS8vHqbguIRoYMgGAXn7xur+ZCA25vIowMydHO0R4P+x0NuV4lTXwaiQjexZWEyMjF7FnZj8vHQrjwHv4BtNeNpQXar/oqF8nYbprNjrQJxheGTkPHmb5kCu2E=
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=iteam1337/sonos-wejay
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
    ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
