version: '3'

services:
  wejay:
    image: iteam1337/sonos-wejay:latest
    ports:
      - 80:3000
    networks:
      - wejay
    environment:
      - SPOTIFY_ID=${SPOTIFY_ID}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
      - SLACK_TOKEN=${SLACK_TOKEN}

  mysql:
    image: mysql
    ports:
      - 3306:3306
    networks:
      - wejay
    environment:
      - MYSQL_DATABASE=wejay
      - MYSQL_USER=wejay
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

networks:
  wejay:
    external: true
