version: '3'

services:
  wejay:
    image: iteam1337/sonos-wejay:latest
    ports:
      - 80:3000
    networks:
      - wejay
    environment:
      - SPOTIFY_ID=${SPOTIFY_ID}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
      - SLACK_TOKEN=${SLACK_TOKEN}
      - WEJAY_IP=${WEJAY_IP}

networks:
  wejay:
    external: true
